# Generated by Django 5.0.7 on 2025-10-05 23:16

from django.db import migrations

def populate_bncc_data(apps, schema_editor):
    AreaBNCC = apps.get_model('api', 'AreaBNCC')
    Subject = apps.get_model('api', 'Subject')

    areas_subjects = {
        "Linguagens, Códigos e suas Tecnologias": ["Português", "Inglês", "Literatura"],
        "Matemática e suas Tecnologias": ["Matemática"],
        "Ciências da Natureza e suas Tecnologias": ["Biologia", "Física", "Química"],
        "Ciências Humanas e Sociais Aplicadas": ["História", "Geografia", "Sociologia", "Filosofia"],
        "Conhecimentos Gerais": ["Informática", "Lógica"]
    }

    for area_name, subjects_list in areas_subjects.items():
        area, created = AreaBNCC.objects.get_or_create(name=area_name)
        for subject_name in subjects_list:
            Subject.objects.get_or_create(name=subject_name, area=area)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activitylog'),
    ]

    operations = [
        migrations.RunPython(populate_bncc_data),
    ]