# Generated by Django 5.0.7 on 2025-10-06 00:21

from django.db import migrations

def populate_quests(apps, schema_editor):
    Quest = apps.get_model('api', 'Quest')
    quests_data = [
        {
            "id": "complete_3_blocks",
            "description": "Completar 3 blocos de perguntas.",
            "xp_reward": 50,
            "type": "daily"
        },
        {
            "id": "correct_20_questions",
            "description": "Acertar 20 perguntas.",
            "xp_reward": 30,
            "type": "daily"
        },
        {
            "id": "login_streak",
            "description": "Manter a sequência de login (entrar no app todos os dias).",
            "xp_reward": 20,
            "type": "daily"
        }
    ]
    for quest_data in quests_data:
        Quest.objects.get_or_create(id=quest_data['id'], defaults=quest_data)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_achievement_quest_gamification_userachievement_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_quests),
    ]