# Generated by Django 5.2.7 on 2025-10-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_populate_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
