# Generated by BLACKBOXAI on 2025-10-13
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fix_userprofile_fk_cascade'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE api_userquest DROP CONSTRAINT IF EXISTS api_userquest_user_id_b699e354_fk_auth_user_id;
            ALTER TABLE api_userquest ADD CONSTRAINT api_userquest_user_id_b699e354_fk_auth_user_id
            FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE api_userquest DROP CONSTRAINT IF EXISTS api_userquest_user_id_b699e354_fk_auth_user_id;
            ALTER TABLE api_userquest ADD CONSTRAINT api_userquest_user_id_b699e354_fk_auth_user_id
            FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE PROTECT;
            """
        ),
    ]
