# Generated by Django 5.2.7 on 2025-10-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fix_all_fk_cascade'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='userachievement',
        #     name='achievement',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='activitylog',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='activitylog',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='subject',
        #     name='area',
        # ),
        # migrations.RemoveField(
        #     model_name='gamification',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='userquest',
        #     name='quest',
        # ),
        # migrations.RemoveField(
        #     model_name='userperformance',
        #     name='subject',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='userachievement',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='userachievement',
        #     name='user',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='userperformance',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='userperformance',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='user',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='userquest',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='userquest',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='Achievement',
        # ),
        # migrations.DeleteModel(
        #     name='ActivityLog',
        # ),
        # migrations.DeleteModel(
        #     name='AreaBNCC',
        # ),
        # migrations.DeleteModel(
        #     name='Gamification',
        # ),
        # migrations.DeleteModel(
        #     name='Quest',
        # ),
        # migrations.DeleteModel(
        #     name='Subject',
        # ),
        # migrations.DeleteModel(
        #     name='UserAchievement',
        # ),
        # migrations.DeleteModel(
        #     name='UserPerformance',
        # ),
        # migrations.DeleteModel(
        #     name='UserProfile',
        # ),
        # migrations.DeleteModel(
        #     name='UserQuest',
        # ),
    ]
