# Generated by Django 5.2.7 on 2025-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fix_all_fk_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamification',
            name='hearts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gamification',
            name='hearts_last_refill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
