# Generated by Django 5.2.7 on 2025-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gamification_hearts_gamification_hearts_last_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocos_completos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
