# Generated by Django 5.2.7 on 2025-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userprofile_blocos_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
