# Generated by Django 5.2.7 on 2025-11-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='api_activitylog_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='api_activitylog_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamification',
            name='api_gamific_xp_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamification',
            name='api_gamific_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='userperformance',
            name='api_userperf_subj_corr_idx',
        ),
        migrations.RemoveIndex(
            model_name='userquest',
            name='api_userquest_user_date_idx',
        ),
    ]
