# Generated by Django 5.2.6 on 2025-09-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('nivel_dificuldade', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('horas_por_semana', models.PositiveIntegerField(help_text='Horas de estudo por semana')),
                ('duracao_semanas', models.PositiveIntegerField(help_text='Duração do plano em semanas')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('gerado_por_ia', models.BooleanField(default=True)),
                ('prompt_usado', models.TextField(blank=True, help_text='Prompt usado para gerar o plano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplinas', models.ManyToManyField(related_name='planos', to='study_plans.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_estudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Estudo',
                'verbose_name_plural': 'Planos de Estudo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AtividadePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('leitura', 'Leitura'), ('exercicio', 'Exercício'), ('video', 'Vídeo'), ('pratica', 'Prática'), ('revisao', 'Revisão'), ('avaliacao', 'Avaliação')], max_length=20)),
                ('semana', models.PositiveIntegerField(help_text='Semana do plano')),
                ('dia_semana', models.PositiveIntegerField(help_text='Dia da semana (1-7)')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem da atividade no dia')),
                ('tempo_estimado_minutos', models.PositiveIntegerField(help_text='Tempo estimado em minutos')),
                ('recursos_necessarios', models.TextField(blank=True, help_text='Materiais ou recursos necessários')),
                ('links_uteis', models.JSONField(blank=True, default=list, help_text='Links úteis para a atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plans.disciplina')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='study_plans.planoestudo')),
            ],
            options={
                'verbose_name': 'Atividade do Plano',
                'verbose_name_plural': 'Atividades do Plano',
                'ordering': ['semana', 'dia_semana', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tempo_gasto_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('nota_auto_avaliacao', models.PositiveIntegerField(blank=True, help_text='Nota de 1 a 5 que o usuário se dá', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='study_plans.atividadeplano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Usuário',
                'verbose_name_plural': 'Progressos dos Usuários',
                'unique_together': {('usuario', 'atividade')},
            },
        ),
    ]
