# Generated by Django 4.2.24 on 2025-10-01 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('quiz_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='planoestudo',
            name='disciplinas',
        ),
        migrations.RemoveField(
            model_name='planoestudo',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='progressousuario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AtividadePlano',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='PlanoEstudo',
        ),
        migrations.DeleteModel(
            name='ProgressoUsuario',
        ),
    ]
