"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!0$7hljbrd1+olf1i9^nl3r2#fcrna((=3)e^474d-+j&npax-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.0.89,*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
    'api',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir arquivos estáticos em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Suporte para DATABASE_URL (Render/Heroku) ou configuração manual (AWS RDS)
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgresql://{os.environ.get('DB_USER', 'postgres')}:{os.environ.get('DB_PASSWORD')}@{os.environ.get('DB_HOST', 'database-1.ctg0eyqokqwa.us-east-2.rds.amazonaws.com')}:{os.environ.get('DB_PORT', '5432')}/{os.environ.get('DB_NAME', 'postgres')}",
        conn_max_age=600,
        ssl_require=False
    )
}

# Suporte para psycopg3 (Python 3.14+)
# O Django 5.2+ suporta tanto psycopg2 quanto psycopg3
try:
    import psycopg  # psycopg3
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
except ImportError:
    try:
        import psycopg2  # psycopg2
        DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    except ImportError:
        pass  # Sem driver PostgreSQL instalado

# Configurações otimizadas para AWS RDS com alta latência
DATABASES['default']['OPTIONS'] = {
    'connect_timeout': 30,  # Timeout de conexão (30 segundos)
    'options': '-c statement_timeout=300000'  # Timeout de query (5 minutos)
}
DATABASES['default']['CONN_MAX_AGE'] = 0  # Desabilita pool persistente para evitar conexões travadas


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise - Configuração para servir arquivos estáticos eficientemente
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# SIMPLE JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),  # Token expira em 2 horas
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token expira em 7 dias
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# CORS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins - Permite requisições de rede local
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Adiciona IPs da rede local dinamicamente
import socket
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    CSRF_TRUSTED_ORIGINS.extend([
        f'http://{local_ip}:8080',
        f'http://{local_ip}:5173',
    ])
except:
    pass

# Adiciona origens do ambiente (para produção)
env_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if env_origins:
    CSRF_TRUSTED_ORIGINS.extend(env_origins.split(','))

# CELERY
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Gamification defaults
# Number of minutes required to refill 1 heart when the user is out of lives
GAMIFICATION_REFILL_MINUTES = int(os.environ.get('GAMIFICATION_REFILL_MINUTES', '3'))

# --- Supabase Storage Configuration (using S3 backend) --- (Commented out since saving images in DB)

# Extract Supabase Project ID from URL for convenience
# SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
# SUPABASE_PROJECT_ID = ''
# if SUPABASE_URL:
#     SUPABASE_PROJECT_ID = SUPABASE_URL.split('.')[0].replace('https://', '')

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# The following settings are used by the S3 backend
# AWS_ACCESS_KEY_ID = SUPABASE_PROJECT_ID # Your Supabase Project ID
# AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_SERVICE_KEY') # Your Supabase service_role key
# AWS_STORAGE_BUCKET_NAME = os.environ.get('BUCKET_NAME') # Your Supabase bucket name
# AWS_S3_ENDPOINT_URL = f'https://{SUPABASE_PROJECT_ID}.supabase.co/storage/v1' # Supabase S3 endpoint

# AWS_S3_FILE_OVERWRITE = False # Do not overwrite files with the same name
# AWS_DEFAULT_ACL = 'public-read' # Make files public by default
# AWS_S3_REGION_NAME = 'us-east-1' # Optional: Specify a region

# API Keys
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')

# SWAGGER / OpenAPI Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

# LOGGING Configuration for Performance Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Database Query Performance Settings
# In DEBUG mode, log queries that take longer than this threshold (in seconds)
if DEBUG:
    # Show SQL queries in console for debugging
    # LOGGING['loggers']['django.db.backends']['level'] = 'DEBUG'
    pass


# ==================== AWS Cognito Configuration ====================
# Configure estas variáveis no arquivo .env ou nas variáveis de ambiente
AWS_COGNITO_REGION = os.environ.get('AWS_COGNITO_REGION', 'us-east-1')
AWS_COGNITO_USER_POOL_ID = os.environ.get('AWS_COGNITO_USER_POOL_ID', '')
AWS_COGNITO_APP_CLIENT_ID = os.environ.get('AWS_COGNITO_APP_CLIENT_ID', '')
AWS_COGNITO_APP_CLIENT_SECRET = os.environ.get('AWS_COGNITO_APP_CLIENT_SECRET', '')
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')

# ==================== EmailJS Configuration ====================
# Para envio de emails de recuperação de senha
EMAILJS_SERVICE_ID = os.environ.get('EMAILJS_SERVICE_ID', '')
EMAILJS_TEMPLATE_ID = os.environ.get('EMAILJS_TEMPLATE_ID', '')
EMAILJS_USER_ID = os.environ.get('EMAILJS_USER_ID', '')
